http{

    #frontend и backend конфигурация
    server{
        
        listen 80;
        server_name ://weather-frontend-fvss.onrender.com;

        location / {
            root var/www/frontend;
            index index.html
        }

        location /weather {
            proxy_pass http://backend:8000; # "backend" — имя сервиса из docker-compose
            
            # Передаем реальный IP пользователя в заголовках. 
            # Программисты смогут вытащить его через request.headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}