name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install requirements
        run: pip install pytest httpx fastapi -r backend/requirements.txt
      
      - name: Run tests
        run: pytest backend/tests/ -v 
      
      
      
